var express = require("express");
var cors = require("cors");
var app = express();
app.set("port", process.env.PORT || 4000);
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cors());
app.use("/api/v1/nfts", require("./src/routers/nftRoutes"));
app.use("/api/v1/users", require("./src/routers/userRoutes"));
module.exports = app;
